# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "packet-core-control-plane show",
)
class Show(AAZCommand):
    """Get information about the specified packet core control plane.
    """

    _aaz_info = {
        "version": "2022-04-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.mobilenetwork/packetcorecontrolplanes/{}", "2022-04-01-preview"],
        ]
    }

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.packet_core_control_plane_name = AAZStrArg(
            options=["-n", "--name", "--packet-core-control-plane-name"],
            help="The name of the packet core control plane.",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9][a-zA-Z0-9_-]*$",
                max_length=64,
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.PacketCoreControlPlanesGet(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class PacketCoreControlPlanesGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MobileNetwork/packetCoreControlPlanes/{packetCoreControlPlaneName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "packetCoreControlPlaneName", self.ctx.args.packet_core_control_plane_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2022-04-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.identity = AAZObjectType()
            _schema_on_200.location = AAZStrType(
                flags={"required": True},
            )
            _schema_on_200.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.properties = AAZObjectType(
                flags={"required": True, "client_flatten": True},
            )
            _schema_on_200.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"client_flatten": True, "read_only": True},
            )
            _schema_on_200.tags = AAZDictType()
            _schema_on_200.type = AAZStrType(
                flags={"read_only": True},
            )

            identity = cls._schema_on_200.identity
            identity.principal_id = AAZStrType(
                serialized_name="principalId",
                flags={"read_only": True},
            )
            identity.tenant_id = AAZStrType(
                serialized_name="tenantId",
                flags={"read_only": True},
            )
            identity.type = AAZStrType(
                flags={"required": True},
            )
            identity.user_assigned_identities = AAZDictType(
                serialized_name="userAssignedIdentities",
            )

            user_assigned_identities = cls._schema_on_200.identity.user_assigned_identities
            user_assigned_identities.Element = AAZObjectType()

            _element = cls._schema_on_200.identity.user_assigned_identities.Element
            _element.client_id = AAZStrType(
                serialized_name="clientId",
                flags={"read_only": True},
            )
            _element.principal_id = AAZStrType(
                serialized_name="principalId",
                flags={"read_only": True},
            )

            properties = cls._schema_on_200.properties
            properties.control_plane_access_interface = AAZObjectType(
                serialized_name="controlPlaneAccessInterface",
                flags={"required": True},
            )
            properties.core_network_technology = AAZStrType(
                serialized_name="coreNetworkTechnology",
            )
            properties.local_diagnostics_access = AAZObjectType(
                serialized_name="localDiagnosticsAccess",
            )
            properties.mobile_network = AAZObjectType(
                serialized_name="mobileNetwork",
                flags={"required": True},
            )
            properties.platform = AAZObjectType()
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )
            properties.sku = AAZStrType(
                flags={"required": True},
            )
            properties.version = AAZStrType()

            control_plane_access_interface = cls._schema_on_200.properties.control_plane_access_interface
            control_plane_access_interface.ipv4_address = AAZStrType(
                serialized_name="ipv4Address",
            )
            control_plane_access_interface.ipv4_gateway = AAZStrType(
                serialized_name="ipv4Gateway",
            )
            control_plane_access_interface.ipv4_subnet = AAZStrType(
                serialized_name="ipv4Subnet",
            )
            control_plane_access_interface.name = AAZStrType()

            local_diagnostics_access = cls._schema_on_200.properties.local_diagnostics_access
            local_diagnostics_access.https_server_certificate = AAZObjectType(
                serialized_name="httpsServerCertificate",
            )

            https_server_certificate = cls._schema_on_200.properties.local_diagnostics_access.https_server_certificate
            https_server_certificate.certificate_url = AAZStrType(
                serialized_name="certificateUrl",
            )

            mobile_network = cls._schema_on_200.properties.mobile_network
            mobile_network.id = AAZStrType(
                flags={"required": True},
            )

            platform = cls._schema_on_200.properties.platform
            platform.azure_stack_edge_device = AAZObjectType(
                serialized_name="azureStackEdgeDevice",
            )
            platform.connected_cluster = AAZObjectType(
                serialized_name="connectedCluster",
            )
            platform.custom_location = AAZObjectType(
                serialized_name="customLocation",
            )
            platform.type = AAZStrType(
                flags={"required": True},
            )

            azure_stack_edge_device = cls._schema_on_200.properties.platform.azure_stack_edge_device
            azure_stack_edge_device.id = AAZStrType(
                flags={"required": True},
            )

            connected_cluster = cls._schema_on_200.properties.platform.connected_cluster
            connected_cluster.id = AAZStrType(
                flags={"required": True},
            )

            custom_location = cls._schema_on_200.properties.platform.custom_location
            custom_location.id = AAZStrType(
                flags={"required": True},
            )

            system_data = cls._schema_on_200.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
            )

            tags = cls._schema_on_200.tags
            tags.Element = AAZStrType()

            return cls._schema_on_200


__all__ = ["Show"]
