apiVersion: v1
kind: Pod
metadata:
  name: special-env-regex
spec:
  containers:
    - name: app
      image: mcr.microsoft.com/azurelinux/distroless/base@sha256:1e77d97e1e39f22ed9c52f49b3508b4c1044cec23743df9098ac44e025f654f2
      env:
        - name: THIM_ENDPOINT
          value: "===VIRTUALNODE2.CC.THIM.TEST==="
        - name: APP_MODE
          value: "production"
