name: $(Date:yyyyMMdd)$(Rev:.r-).CleanUp

trigger: none

pool:
  name: $(1ES_DevInfra_Auto_TearDown_Pool_Name)

variables:
  - group: "AZCLI AKS Live Test"
  - name: LIVE_TEST_BASE_DIR
    value: "src/aks-preview/azcli_aks_live_test"

jobs:
- job: CleanUp
  timeoutInMinutes: 60
  displayName: "Clean Up"
  steps:
    - bash: |
        $(LIVE_TEST_BASE_DIR)/scripts/clean_up.sh
      displayName: "Clean up outdated resource groups"
