name: $(Date:yyyyMMdd)$(Rev:.r)_Python$(PYTHON_VERSION)_Coverage-$(COVERAGE)_Mode-$(TEST_MODE)

trigger: none

pool:
  name: $(1ES_DevInfra_Auto_TearDown_Pool_Name)

pr:
  branches:
    include:
    - main
  paths:
    include:
    - src/aks-preview/

variables:
  - group: azcli-aks-tool
  - name: ContainerName
    value: "azcli-aks-live-test"
  - name: REPO_NAME
    value: "azure-cli-extensions"
  - name: LIVE_TEST_BASE_DIR
    value: "azure-cli-extensions/src/aks-preview/azcli_aks_live_test"
  - name: ACS_BASE_DIR
    value: "azure-cli/src/azure-cli/azure/cli/command_modules/acs"
  - name: AKS_PREVIEW_BASE_DIR
    value: "azure-cli-extensions/src/aks-preview/azext_aks_preview"

jobs:
- job: LiveTest
  timeoutInMinutes: 360
  displayName: "Live Test with Python"
  steps:
    - bash: |
        mkdir $(REPO_NAME)
        shopt -s extglob dotglob
        mv !($(REPO_NAME)) $(REPO_NAME)
        shopt -u extglob dotglob
      displayName: "Move All Files to a Subdirectory"
    - bash: |
        $(LIVE_TEST_BASE_DIR)/scripts/clone_repo.sh
      condition: succeeded()
      displayName: "Clone GitHub Repo(s) and Extract Test Scripts"
    - bash: |
        ./scripts/prepare_image.sh
      condition: succeeded()
      displayName: "Prepare Test Image"
    - bash: |
        ./scripts/start_container.sh $(ContainerName)
      env:
        MAPPED_AZCLI_ALT_CLIENT_SECRET: $(AZCLI_ALT_CLIENT_SECRET)
        BUILD_REASON: $(Build.Reason)
        SYSTEM_PULLREQUEST_TARGETBRANCH: $(System.PullRequest.TargetBranch)
      condition: succeeded()
      displayName: "Start Container"
    - bash: |
        docker exec $(ContainerName) /opt/scripts/setup_venv.sh setup-tool y y /az_aks_tool-latest-py3-none-any.whl
        docker exec $(ContainerName) /opt/scripts/setup_venv.sh setup-az n azure-cli/ azure-cli-extensions/
      condition: succeeded()
      displayName: "Set up Virtual Environment"
    - bash: |
        docker exec $(ContainerName) /opt/scripts/test_cli_live.sh
      condition: and(succeeded(), in(variables['COVERAGE'], 'cli', 'all'))
      displayName: Perform Live Test for CLI
    - bash: |
        docker exec $(ContainerName) /opt/scripts/test_ext_live.sh
      condition: and(succeededOrFailed(), in(variables['COVERAGE'], 'ext', 'all'))
      displayName: Perform Live Test for EXT
    - task: CopyFiles@2
      inputs:
        contents: 'reports/**'
        flattenFolders: true
        targetFolder: $(Build.ArtifactStagingDirectory)
      condition: succeededOrFailed()
      displayName: "Copy Reports & Logs"
    - bash: mkdir -p $(Build.ArtifactStagingDirectory)/cli-recordings $(Build.ArtifactStagingDirectory)/ext-recordings
      condition: succeededOrFailed()
      displayName: "Create Dir for Recordings"
    - task: CopyFiles@2
      inputs:
        contents: '$(ACS_BASE_DIR)/tests/latest/recordings/updated/**'
        flattenFolders: true
        targetFolder: $(Build.ArtifactStagingDirectory)/cli-recordings
      condition: and(succeededOrFailed(), in(variables['COVERAGE'], 'cli', 'all'))
      displayName: "Copy CLI Recordings"
    - task: CopyFiles@2
      inputs:
        contents: '$(AKS_PREVIEW_BASE_DIR)/tests/latest/recordings/updated/**'
        flattenFolders: true
        targetFolder: $(Build.ArtifactStagingDirectory)/ext-recordings
      condition: and(succeededOrFailed(), in(variables['COVERAGE'], 'ext', 'all'))
      displayName: "Copy EXT Recordings"
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: 'live test reports'
      condition: succeededOrFailed()
