version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: wei:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: k8s-configuration
    upstream: master        # Required. Can be a branch in the same forked repo.
  - base: k8s-extension/private-preview
    upstream: master        # Required. Can be a branch in the same forked repo.
  - base: k8s-extension/public-preview
    upstream: master        # Required. Can be a branch in the same forked repo.
