apiVersion: v1
kind: Pod
metadata:
  name: seccomp-profile
spec:
  containers:
    - name: app
      image: mcr.microsoft.com/azurelinux/distroless/base@sha256:1e77d97e1e39f22ed9c52f49b3508b4c1044cec23743df9098ac44e025f654f2
      securityContext:
        seccompProfile: eyJkZWZhdWx0QWN0aW9uIjoiU0NNUF9BQ1RfRVJSTk8iLCJkZWZhdWx0RXJybm9SZXQiOjEsInN5c2NhbGxzIjpbeyJuYW1lcyI6WyJyZWFkIiwid3JpdGUiXSwiYWN0aW9uIjoiU0NNUF9BQ1RfQUxMT1cifV19
      command:
        - /bin/sh
      args:
        - -c
        - echo hello
      env:
        - name: APP_MODE
          value: production
