apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-chart.fullname" . }}
  labels:
    {{- include "sample-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONFIG_NAME
              value: {{ .Values.config.name }}
            - name: CONFIG_VERSION
              value: {{ .Values.config.version }}
            - name: FEATURE1_ENABLED
              value: "{{ .Values.config.settings.feature1 }}"
            - name: FEATURE2_ENABLED
              value: "{{ .Values.config.settings.feature2 }}"
