apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kms-localvault
    tier: control-plane
  name: kms-localvault
  namespace: kube-system
spec:
  containers:
  - name: kms-localvault
    image: __KMS_IMAGE_PATH__
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: KMS_PROVIDER
        value: localvault
      - name: CC_ARM_ID
        value: __CC_ARM_ID__
    volumeMounts:
    - name: host-sock
      mountPath: /var/run
    - name: kubeconfig
      mountPath: /etc/kubernetes/admin.conf
  volumes:
  - hostPath:
      path: /run
      type: Directory
    name: host-sock
  - hostPath:
      path: __KUBECONFIG_PATH__
    name: kubeconfig