apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-clusterconfig
  namespace: azure-arc
data:
  AZURE_RESOURCE_NAME: {{ .Values.global.resourceName }}
  AZURE_SUBSCRIPTION_ID: {{ .Values.global.subscriptionId }}
  AZURE_TENANT_ID: {{ .Values.global.tenantId }}
  AZURE_CLIENT_ID: {{ .Values.global.clientId }}
  AZURE_RESOURCE_GROUP: {{ .Values.global.resourceGroupName }}
  AZURE_REGION: {{ .Values.global.location }}
  ONBOARDING_SECRET_NAME: "azure-arc-connect-privatekey"
  ONBOARDING_SECRET_NAMESPACE: "azure-arc"
  MANAGED_IDENTITY_AUTH: "{{ .Values.systemDefaultValues.optIn.ManagedIdentityAuth }}"
  CLUSTER_TYPE: {{ index .Values.systemDefaultValues "config-agent" "cluster_type" }}{{ if index .Values.systemDefaultValues "config-agent" "dp_endpoint_override" }}
  DP_ENDPOINT_OVERRIDE: {{ index .Values.systemDefaultValues "config-agent" "dp_endpoint_override" }}{{ end }}
  FLUX_CLIENT_DEFAULT_LOCATION: {{ index .Values.systemDefaultValues "config-agent" "flux_client_default_location" }}
  AZURE_ARC_AGENT_VERSION: {{ .Values.systemDefaultValues.azureArcAgents.version }}
  ARC_AGENT_HELM_CHART_NAME: "{{ .Chart.Name }}"
  HELM_AUTO_UPDATE_CHECK_FREQUENCY_IN_MINUTES: "{{ .Values.global.UpdateCheckFrequencyInMinutes }}"
  AZURE_ARC_AUTOUPDATE: "{{ .Values.global.autoUpdate }}"
  ARC_AGENT_RELEASE_TRAIN: {{.Values.global.releaseTrain}}
  AZURE_ARC_RELEASE_NAME: "{{ .Release.Name }}"
  AZURE_ARC_HELM_NAMESPACE: "{{ .Release.Namespace }}"
  DEBUG_LOGGING: "{{ .Values.systemDefaultValues.debugLogging }}"
