apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-fluentd-config
  namespace: azure-arc
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         300
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   Off
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE output.conf
 
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               azure-arc.*
        Path              /var/log/containers/*azure-arc*.log
        Parser            docker
        Mem_Buf_Limit     1MB
 
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
  
  output.conf: |
    [OUTPUT]
        Name        http_mdm
        Match       *
        Id          http_mdm_plugin
  
