apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-agent
  namespace: azure-arc
  labels:
    app.kubernetes.io/name:  azure-arc-k8s
    app.kubernetes.io/component: connect-agent
  annotations:
    description: {{ .Chart.Description }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: connect-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: connect-agent
    spec:
      serviceAccountName: azure-arc-operatorsa
      containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https      
        - name: connect-agent
          image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "connect-agent" "image" }}:{{ index .Values.systemDefaultValues "connect-agent" "tag" }}"
          imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
          envFrom:
          - configMapRef:
              name: azure-clusterconfig
          env:
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: azure-arc-onboarding
                key: value
          {{ if .Values.systemDefaultValues.IsDebug}}
          ports:
            - containerPort: 40000
              name: debug
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
        {{end}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: connect-agent
  name: connect-agent-metrics-service
  namespace: azure-arc
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: connect-agent                