apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: azure-arc
  labels:
    app.kubernetes.io/name:  azure-arc-k8s
    app.kubernetes.io/component: fluent-bit
  annotations:
    description: {{ .Chart.Description }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: fluent-bit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: fluent-bit
    spec:
      serviceAccountName: azure-arc-operatorsa
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - azure-arc-k8s
            topologyKey: "kubernetes.io/hostname"
            namespaces:
            - azure-arc
      containers:
      - name: fluent-bit
        image: "{{ .Values.systemDefaultValues.image.repository }}/{{ .Values.systemDefaultValues.image.releaseName }}/{{ index .Values.systemDefaultValues "fluent-bit" "image" }}:{{ index .Values.systemDefaultValues "fluent-bit" "tag" }}"
        imagePullPolicy: {{ .Values.systemDefaultValues.image.imagePullPolicy }}
        envFrom:
          - configMapRef:
              name: azure-clusterconfig
        ports:
        - containerPort: 2020    
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentbit-clusterconfig
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentbit-clusterconfig
        configMap:
          name: azure-fluentd-config
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule