apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-arc-troubleshoot-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-reader
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: azure-arc-troubleshoot-sa
  namespace: default
roleRef:
  kind: Role 
  name: secret-reader 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: azure-arc-diagnoser-job
  namespace: default
  labels:
    app: networktest
spec:
  template:
    metadata:
      labels:
        app: networktest
    spec:
      serviceAccountName: azure-arc-troubleshoot-sa
      containers: 
      - name: azure-arc-diagnoser-container
        image: svacr1.azurecr.io/test:35.0
      restartPolicy: Never
  backoffLimit: 4
