---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-arc-troubleshoot-sa
  namespace: azure-arc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: default
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets-rolebindings
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: azure-arc-troubleshoot-sa
  namespace: azure-arc
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: Azure-Diagnoser
  name: azure-arc-diagnoser-job
  namespace: azure-arc
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: Arc-Diagnoser
    spec:
      containers:
      - args:
        - default
        command:
        - /bin/bash
        - /diagnoser_job_script.sh
        image: mcr.microsoft.com/arck8sdiagnoser:v0.1.0
        name: azure-arc-diagnoser-container
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 13243 #Random non-root user and group to avoid default 0 which is root
          runAsGroup: 12434
      restartPolicy: Never
      serviceAccountName: azure-arc-troubleshoot-sa
