# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

import os
from azure.cli.testsdk import ScenarioTest
from azure.cli.testsdk import ResourceGroupPreparer
from .preparers import VirtualNetworkPreparer
from .example_steps import step_controller_create
from .example_steps import step_controller_show
from .example_steps import step_delegated_subnet_service_create
from .example_steps import step_delegated_subnet_service_list
from .example_steps import step_delegated_subnet_service_show
from .example_steps import step_orchestrator_instance_service_create
from .example_steps import step_orchestrator_instance_service_show
from .example_steps import step_orchestrator_instance_service_list
from .example_steps import step_orchestrator_instance_service_list2
from .example_steps import step_orchestrator_instance_service_delete
from .example_steps import step_controller_delete
from .example_steps import step_delegated_network_list
from .example_steps import step_delegated_network_list2
from .example_steps import step_delegated_subnet_service_list2
from .example_steps import step_delegated_subnet_service_delete
from .. import (
    try_manual,
    raise_if,
    calc_coverage
)


TEST_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '..'))


# Env setup_scenario
@try_manual
def setup_scenario(test, rg, rg_2):
    pass


# Env cleanup_scenario
@try_manual
def cleanup_scenario(test, rg, rg_2):
    pass


# Testcase: Scenario
@try_manual
def call_scenario(test, rg, rg_2):
    setup_scenario(test, rg, rg_2)
    step_controller_create(test, rg, rg_2, checks=[])
    step_controller_show(test, rg, rg_2, checks=[])
    step_delegated_subnet_service_create(test, rg, rg_2, checks=[])
    step_delegated_subnet_service_list(test, rg, rg_2, checks=[])
    step_delegated_subnet_service_show(test, rg, rg_2, checks=[])
    step_orchestrator_instance_service_create(test, rg, rg_2, checks=[])
    step_orchestrator_instance_service_show(test, rg, rg_2, checks=[])
    step_orchestrator_instance_service_list(test, rg, rg_2, checks=[])
    step_orchestrator_instance_service_list2(test, rg, rg_2, checks=[])
    step_orchestrator_instance_service_delete(test, rg, rg_2, checks=[])
    step_controller_delete(test, rg, rg_2, checks=[])
    step_delegated_network_list(test, rg, rg_2, checks=[])
    step_delegated_network_list2(test, rg, rg_2, checks=[])
    step_delegated_subnet_service_list2(test, rg, rg_2, checks=[])
    step_delegated_subnet_service_delete(test, rg, rg_2, checks=[])
    cleanup_scenario(test, rg, rg_2)


# Test class for Scenario
@try_manual
class DncScenarioTest(ScenarioTest):

    def __init__(self, *args, **kwargs):
        super(DncScenarioTest, self).__init__(*args, **kwargs)
        self.kwargs.update({
            'subscription_id': self.get_subscription_id()
        })

        self.kwargs.update({
            'myController': 'testcontroller',
            'myController2': 'dnctestcontroller',
        })


    @ResourceGroupPreparer(name_prefix='clitestdnc_TestRG'[:7], key='rg', parameter_name='rg')
    @ResourceGroupPreparer(name_prefix='clitestdnc_testRG'[:7], key='rg_2', parameter_name='rg_2')
    @VirtualNetworkPreparer(name_prefix='clitestdnc_testvnet'[:7], key='vn', resource_group_key='rg')
    def test_dnc_Scenario(self, rg, rg_2):
        call_scenario(self, rg, rg_2)
        calc_coverage(__file__)
        raise_if()

