CLIENT_PROXY_VERSION = "1.3.017131"
CLIENT_PROXY_RELEASE = "release10-09-21"
CLIENT_PROXY_STORAGE_URL = "https://sshproxysa.blob.core.windows.net"
CLEANUP_TOTAL_TIME_LIMIT_IN_SECONDS = 120
CLEANUP_TIME_INTERVAL_IN_SECONDS = 10
