parameters:
  - name: CLIRepoPath
    type: string
    default: './azure-cli'
  - name: CLIExtensionRepoPath
    type: string
    default: '.'
steps:
  - bash: |
      set -ev

      python -m venv env
      chmod +x env/bin/activate
      . env/bin/activate
      pwd
      ls
      cd ..
      # clone azure-cli
      pwd
      git clone https://github.com/Azure/azure-cli.git ./azure-cli
      python -m pip install -U pip
      pip install azdev
      azdev --version
      azdev setup -c $CLI_REPO_PATH -r $CLI_EXT_REPO_PATH --debug
    displayName: 'azdev setup'
    env:
      CLI_REPO_PATH: ${{ parameters.CLIRepoPath }}
      CLI_EXT_REPO_PATH: ${{ parameters.CLIExtensionRepoPath }}
