parameters:
  - name: CLIRepoPath
    type: string
    default: '../azure-cli'
  - name: CLIExtensionRepoPath
    type: string
    default: './'
steps:
  - bash: |
      set -ev
      python -m venv env
      chmod +x env/bin/activate
      source ./env/bin/activate
      # clone azure-cli
      git clone -q --single-branch -b dev https://github.com/Azure/azure-cli.git ../azure-cli
      python -m pip install -U pip
      pip install azdev
      azdev --version
      azdev setup -c $CLI_REPO_PATH -r $CLI_EXT_REPO_PATH --debug
      # Installing setuptools with a version higher than 70.0.0 will not generate metadata.json
      pip install setuptools==70.0.0
      pip list -v
      az --version
    displayName: 'azdev setup'
    env:
      CLI_REPO_PATH: ${{ parameters.CLIRepoPath }}
      CLI_EXT_REPO_PATH: ${{ parameters.CLIExtensionRepoPath }}