apiVersion: v1
kind: Pod
metadata:
  name: security-context-merge
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1001
  containers:
    - name: app
      image: mcr.microsoft.com/azurelinux/distroless/base@sha256:1e77d97e1e39f22ed9c52f49b3508b4c1044cec23743df9098ac44e025f654f2
      securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false
