# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "palo-alto cloudngfw global-rulestack update",
)
class Update(AAZCommand):
    """Update a GlobalRulestackResource
    """

    _aaz_info = {
        "version": "2022-08-29",
        "resources": [
            ["mgmt-plane", "/providers/paloaltonetworks.cloudngfw/globalrulestacks/{}", "2022-08-29"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    AZ_SUPPORT_GENERIC_UPDATE = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.global_rulestack_name = AAZStrArg(
            options=["--global-rulestack-name"],
            help="GlobalRulestack resource name",
            required=True,
        )

        # define Arg Group "Resource"

        _args_schema = cls._args_schema
        _args_schema.identity = AAZObjectArg(
            options=["--identity"],
            arg_group="Resource",
            help="The managed service identities assigned to this resource.",
            nullable=True,
        )
        _args_schema.location = AAZResourceLocationArg(
            arg_group="Resource",
            help="Global Location",
        )

        identity = cls._args_schema.identity
        identity.type = AAZStrArg(
            options=["type"],
            help="The type of managed identity assigned to this resource.",
            enum={"None": "None", "SystemAssigned": "SystemAssigned", "SystemAssigned,UserAssigned": "SystemAssigned,UserAssigned", "UserAssigned": "UserAssigned"},
        )
        identity.user_assigned_identities = AAZDictArg(
            options=["user-assigned-identities"],
            help="The identities assigned to this resource by the user.",
            nullable=True,
        )

        user_assigned_identities = cls._args_schema.identity.user_assigned_identities
        user_assigned_identities.Element = AAZObjectArg(
            nullable=True,
        )

        _element = cls._args_schema.identity.user_assigned_identities.Element
        _element.client_id = AAZStrArg(
            options=["client-id"],
            help="The active directory client identifier for this principal.",
            nullable=True,
        )
        _element.principal_id = AAZStrArg(
            options=["principal-id"],
            help="The active directory identifier for this principal.",
            nullable=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.GlobalRulestackGet(ctx=self.ctx)()
        self.pre_instance_update(self.ctx.vars.instance)
        self.InstanceUpdateByJson(ctx=self.ctx)()
        self.InstanceUpdateByGeneric(ctx=self.ctx)()
        self.post_instance_update(self.ctx.vars.instance)
        yield self.GlobalRulestackCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    @register_callback
    def pre_instance_update(self, instance):
        pass

    @register_callback
    def post_instance_update(self, instance):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class GlobalRulestackGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/providers/PaloAltoNetworks.Cloudngfw/globalRulestacks/{globalRulestackName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "globalRulestackName", self.ctx.args.global_rulestack_name,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2022-08-29",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _UpdateHelper._build_schema_global_rulestack_resource_read(cls._schema_on_200)

            return cls._schema_on_200

    class GlobalRulestackCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/providers/PaloAltoNetworks.Cloudngfw/globalRulestacks/{globalRulestackName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "globalRulestackName", self.ctx.args.global_rulestack_name,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2022-08-29",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=self.ctx.vars.instance,
            )

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _UpdateHelper._build_schema_global_rulestack_resource_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class InstanceUpdateByJson(AAZJsonInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance(self.ctx.vars.instance)

        def _update_instance(self, instance):
            _instance_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=instance,
                typ=AAZObjectType
            )
            _builder.set_prop("identity", AAZObjectType, ".identity")
            _builder.set_prop("location", AAZStrType, ".location", typ_kwargs={"flags": {"required": True}})

            identity = _builder.get(".identity")
            if identity is not None:
                identity.set_prop("type", AAZStrType, ".type", typ_kwargs={"flags": {"required": True}})
                identity.set_prop("userAssignedIdentities", AAZDictType, ".user_assigned_identities")

            user_assigned_identities = _builder.get(".identity.userAssignedIdentities")
            if user_assigned_identities is not None:
                user_assigned_identities.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".identity.userAssignedIdentities{}")
            if _elements is not None:
                _elements.set_prop("clientId", AAZStrType, ".client_id")
                _elements.set_prop("principalId", AAZStrType, ".principal_id")

            return _instance_value

    class InstanceUpdateByGeneric(AAZGenericInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance_by_generic(
                self.ctx.vars.instance,
                self.ctx.generic_update_args
            )


class _UpdateHelper:
    """Helper class for Update"""

    _schema_global_rulestack_resource_read = None

    @classmethod
    def _build_schema_global_rulestack_resource_read(cls, _schema):
        if cls._schema_global_rulestack_resource_read is not None:
            _schema.id = cls._schema_global_rulestack_resource_read.id
            _schema.identity = cls._schema_global_rulestack_resource_read.identity
            _schema.location = cls._schema_global_rulestack_resource_read.location
            _schema.name = cls._schema_global_rulestack_resource_read.name
            _schema.properties = cls._schema_global_rulestack_resource_read.properties
            _schema.system_data = cls._schema_global_rulestack_resource_read.system_data
            _schema.type = cls._schema_global_rulestack_resource_read.type
            return

        cls._schema_global_rulestack_resource_read = _schema_global_rulestack_resource_read = AAZObjectType()

        global_rulestack_resource_read = _schema_global_rulestack_resource_read
        global_rulestack_resource_read.id = AAZStrType(
            flags={"read_only": True},
        )
        global_rulestack_resource_read.identity = AAZObjectType()
        global_rulestack_resource_read.location = AAZStrType(
            flags={"required": True},
        )
        global_rulestack_resource_read.name = AAZStrType(
            flags={"read_only": True},
        )
        global_rulestack_resource_read.properties = AAZObjectType(
            flags={"required": True, "client_flatten": True},
        )
        global_rulestack_resource_read.system_data = AAZObjectType(
            serialized_name="systemData",
            flags={"read_only": True},
        )
        global_rulestack_resource_read.type = AAZStrType(
            flags={"read_only": True},
        )

        identity = _schema_global_rulestack_resource_read.identity
        identity.principal_id = AAZStrType(
            serialized_name="principalId",
            flags={"read_only": True},
        )
        identity.tenant_id = AAZStrType(
            serialized_name="tenantId",
            flags={"read_only": True},
        )
        identity.type = AAZStrType(
            flags={"required": True},
        )
        identity.user_assigned_identities = AAZDictType(
            serialized_name="userAssignedIdentities",
        )

        user_assigned_identities = _schema_global_rulestack_resource_read.identity.user_assigned_identities
        user_assigned_identities.Element = AAZObjectType()

        _element = _schema_global_rulestack_resource_read.identity.user_assigned_identities.Element
        _element.client_id = AAZStrType(
            serialized_name="clientId",
        )
        _element.principal_id = AAZStrType(
            serialized_name="principalId",
        )

        properties = _schema_global_rulestack_resource_read.properties
        properties.associated_subscriptions = AAZListType(
            serialized_name="associatedSubscriptions",
        )
        properties.default_mode = AAZStrType(
            serialized_name="defaultMode",
        )
        properties.description = AAZStrType()
        properties.min_app_id_version = AAZStrType(
            serialized_name="minAppIdVersion",
        )
        properties.pan_etag = AAZStrType(
            serialized_name="panEtag",
        )
        properties.pan_location = AAZStrType(
            serialized_name="panLocation",
        )
        properties.provisioning_state = AAZStrType(
            serialized_name="provisioningState",
        )
        properties.scope = AAZStrType()
        properties.security_services = AAZObjectType(
            serialized_name="securityServices",
        )

        associated_subscriptions = _schema_global_rulestack_resource_read.properties.associated_subscriptions
        associated_subscriptions.Element = AAZStrType()

        security_services = _schema_global_rulestack_resource_read.properties.security_services
        security_services.anti_spyware_profile = AAZStrType(
            serialized_name="antiSpywareProfile",
        )
        security_services.anti_virus_profile = AAZStrType(
            serialized_name="antiVirusProfile",
        )
        security_services.dns_subscription = AAZStrType(
            serialized_name="dnsSubscription",
        )
        security_services.file_blocking_profile = AAZStrType(
            serialized_name="fileBlockingProfile",
        )
        security_services.outbound_trust_certificate = AAZStrType(
            serialized_name="outboundTrustCertificate",
        )
        security_services.outbound_un_trust_certificate = AAZStrType(
            serialized_name="outboundUnTrustCertificate",
        )
        security_services.url_filtering_profile = AAZStrType(
            serialized_name="urlFilteringProfile",
        )
        security_services.vulnerability_profile = AAZStrType(
            serialized_name="vulnerabilityProfile",
        )

        system_data = _schema_global_rulestack_resource_read.system_data
        system_data.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        _schema.id = cls._schema_global_rulestack_resource_read.id
        _schema.identity = cls._schema_global_rulestack_resource_read.identity
        _schema.location = cls._schema_global_rulestack_resource_read.location
        _schema.name = cls._schema_global_rulestack_resource_read.name
        _schema.properties = cls._schema_global_rulestack_resource_read.properties
        _schema.system_data = cls._schema_global_rulestack_resource_read.system_data
        _schema.type = cls._schema_global_rulestack_resource_read.type


__all__ = ["Update"]
