# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "changesafety stageprogression update",
)
class Update(AAZCommand):
    """Update a StageProgression
    """

    _aaz_info = {
        "version": "2025-09-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/providers/microsoft.changesafety/changestates/{}/stageprogressions/{}", "2025-09-01-preview"],
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.changesafety/changestates/{}/stageprogressions/{}", "2025-09-01-preview"],
        ]
    }

    AZ_SUPPORT_GENERIC_UPDATE = True

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.change_state_name = AAZStrArg(
            options=["--change-record-name"],
            help="The name of the ChangeState resource.",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-]{3,100}$",
                max_length=100,
                min_length=3,
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg()
        _args_schema.stage_progression_name = AAZStrArg(
            options=["-n", "--name", "--stage-progression-name"],
            help="name of the stageProgression",
            required=True,
            id_part="child_name_1",
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-|]{3,100}$",
                max_length=100,
                min_length=3,
            ),
        )

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.additional_data = AAZObjectArg(
            options=["--additional-data"],
            arg_group="Properties",
            help="Additional metadata for the stageProgression resource.",
            nullable=True,
            blank={},
        )
        _args_schema.comments = AAZStrArg(
            options=["--comments"],
            arg_group="Properties",
            help="Comments about the update to the resource.",
            nullable=True,
            fmt=AAZStrArgFormat(
                max_length=2000,
            ),
        )
        _args_schema.links = AAZListArg(
            options=["--links"],
            arg_group="Properties",
            help="Collection of related links for the change.",
            nullable=True,
        )
        _args_schema.parameters = AAZDictArg(
            options=["--parameters"],
            arg_group="Properties",
            help="Stage specific key value pairs of parameter names & their values for the current Stage, If any.",
            nullable=True,
        )
        _args_schema.stage_reference = AAZStrArg(
            options=["--stage-reference"],
            arg_group="Properties",
            help="Stage name relevant to hierarchical StageMap.",
            fmt=AAZStrArgFormat(
                max_length=200,
                min_length=3,
            ),
        )
        _args_schema.stage_variables = AAZDictArg(
            options=["--stage-variables"],
            arg_group="Properties",
            help="Variables to apply on the change of that stage. Key value pairs supporting any JSON values.",
            nullable=True,
        )
        _args_schema.status = AAZStrArg(
            options=["--status"],
            arg_group="Properties",
            help="StageProgression resource status.",
            enum={"Cancelled": "Cancelled", "Completed": "Completed", "Failed": "Failed", "InProgress": "InProgress", "Initialized": "Initialized", "Paused": "Paused", "Skipped": "Skipped"},
        )

        links = cls._args_schema.links
        links.Element = AAZObjectArg(
            nullable=True,
        )

        _element = cls._args_schema.links.Element
        _element.description = AAZStrArg(
            options=["description"],
            help="Description or note about the link.",
            nullable=True,
            fmt=AAZStrArgFormat(
                max_length=2000,
            ),
        )
        _element.name = AAZStrArg(
            options=["name"],
            help="name of the link.",
        )
        _element.uri = AAZStrArg(
            options=["uri"],
            help="URL or comma separated URLs for the link.",
        )

        parameters = cls._args_schema.parameters
        parameters.Element = AAZAnyTypeArg(
            nullable=True,
        )

        stage_variables = cls._args_schema.stage_variables
        stage_variables.Element = AAZAnyTypeArg(
            nullable=True,
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        condition_0 = has_value(self.ctx.args.change_state_name) and has_value(self.ctx.args.stage_progression_name) and has_value(self.ctx.subscription_id) and has_value(self.ctx.args.resource_group) is not True
        condition_1 = has_value(self.ctx.args.change_state_name) and has_value(self.ctx.args.resource_group) and has_value(self.ctx.args.stage_progression_name) and has_value(self.ctx.subscription_id)
        condition_2 = has_value(self.ctx.args.change_state_name) and has_value(self.ctx.args.stage_progression_name) and has_value(self.ctx.subscription_id) and has_value(self.ctx.args.resource_group) is not True
        condition_3 = has_value(self.ctx.args.change_state_name) and has_value(self.ctx.args.resource_group) and has_value(self.ctx.args.stage_progression_name) and has_value(self.ctx.subscription_id)
        if condition_0:
            self.StageProgressionsGetAtSubscriptionLevel(ctx=self.ctx)()
        if condition_1:
            self.StageProgressionsGet(ctx=self.ctx)()
        self.pre_instance_update(self.ctx.vars.instance)
        self.InstanceUpdateByJson(ctx=self.ctx)()
        self.InstanceUpdateByGeneric(ctx=self.ctx)()
        self.post_instance_update(self.ctx.vars.instance)
        if condition_2:
            self.StageProgressionsCreateOrUpdateAtSubscriptionLevel(ctx=self.ctx)()
        if condition_3:
            self.StageProgressionsCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    @register_callback
    def pre_instance_update(self, instance):
        pass

    @register_callback
    def post_instance_update(self, instance):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class StageProgressionsGetAtSubscriptionLevel(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/providers/Microsoft.ChangeSafety/changeStates/{changeStateName}/stageProgressions/{stageProgressionName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "changeStateName", self.ctx.args.change_state_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "stageProgressionName", self.ctx.args.stage_progression_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-09-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _UpdateHelper._build_schema_stage_progression_read(cls._schema_on_200)

            return cls._schema_on_200

    class StageProgressionsGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ChangeSafety/changeStates/{changeStateName}/stageProgressions/{stageProgressionName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "changeStateName", self.ctx.args.change_state_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "stageProgressionName", self.ctx.args.stage_progression_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-09-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _UpdateHelper._build_schema_stage_progression_read(cls._schema_on_200)

            return cls._schema_on_200

    class StageProgressionsCreateOrUpdateAtSubscriptionLevel(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200, 201]:
                return self.on_200_201(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/providers/Microsoft.ChangeSafety/changeStates/{changeStateName}/stageProgressions/{stageProgressionName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "changeStateName", self.ctx.args.change_state_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "stageProgressionName", self.ctx.args.stage_progression_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-09-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=self.ctx.vars.instance,
            )

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _UpdateHelper._build_schema_stage_progression_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class StageProgressionsCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200, 201]:
                return self.on_200_201(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ChangeSafety/changeStates/{changeStateName}/stageProgressions/{stageProgressionName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "changeStateName", self.ctx.args.change_state_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "stageProgressionName", self.ctx.args.stage_progression_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-09-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=self.ctx.vars.instance,
            )

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _UpdateHelper._build_schema_stage_progression_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class InstanceUpdateByJson(AAZJsonInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance(self.ctx.vars.instance)

        def _update_instance(self, instance):
            _instance_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=instance,
                typ=AAZObjectType
            )
            _builder.set_prop("properties", AAZObjectType)

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("additionalData", AAZObjectType, ".additional_data")
                properties.set_prop("comments", AAZStrType, ".comments")
                properties.set_prop("links", AAZListType, ".links")
                properties.set_prop("parameters", AAZDictType, ".parameters")
                properties.set_prop("stageReference", AAZStrType, ".stage_reference", typ_kwargs={"flags": {"required": True}})
                properties.set_prop("stageVariables", AAZDictType, ".stage_variables")
                properties.set_prop("status", AAZStrType, ".status", typ_kwargs={"flags": {"required": True}})

            links = _builder.get(".properties.links")
            if links is not None:
                links.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".properties.links[]")
            if _elements is not None:
                _elements.set_prop("description", AAZStrType, ".description")
                _elements.set_prop("name", AAZStrType, ".name", typ_kwargs={"flags": {"required": True}})
                _elements.set_prop("uri", AAZStrType, ".uri", typ_kwargs={"flags": {"required": True}})

            parameters = _builder.get(".properties.parameters")
            if parameters is not None:
                parameters.set_elements(AAZAnyType, ".")

            stage_variables = _builder.get(".properties.stageVariables")
            if stage_variables is not None:
                stage_variables.set_elements(AAZAnyType, ".")

            return _instance_value

    class InstanceUpdateByGeneric(AAZGenericInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance_by_generic(
                self.ctx.vars.instance,
                self.ctx.generic_update_args
            )


class _UpdateHelper:
    """Helper class for Update"""

    _schema_stage_progression_read = None

    @classmethod
    def _build_schema_stage_progression_read(cls, _schema):
        if cls._schema_stage_progression_read is not None:
            _schema.id = cls._schema_stage_progression_read.id
            _schema.name = cls._schema_stage_progression_read.name
            _schema.properties = cls._schema_stage_progression_read.properties
            _schema.system_data = cls._schema_stage_progression_read.system_data
            _schema.type = cls._schema_stage_progression_read.type
            return

        cls._schema_stage_progression_read = _schema_stage_progression_read = AAZObjectType()

        stage_progression_read = _schema_stage_progression_read
        stage_progression_read.id = AAZStrType(
            flags={"read_only": True},
        )
        stage_progression_read.name = AAZStrType(
            flags={"read_only": True},
        )
        stage_progression_read.properties = AAZObjectType()
        stage_progression_read.system_data = AAZObjectType(
            serialized_name="systemData",
            flags={"read_only": True},
        )
        stage_progression_read.type = AAZStrType(
            flags={"read_only": True},
        )

        properties = _schema_stage_progression_read.properties
        properties.additional_data = AAZObjectType(
            serialized_name="additionalData",
        )
        properties.comments = AAZStrType()
        properties.links = AAZListType()
        properties.parameters = AAZDictType()
        properties.provisioning_state = AAZStrType(
            serialized_name="provisioningState",
            flags={"read_only": True},
        )
        properties.sequence = AAZIntType(
            flags={"read_only": True},
        )
        properties.stage_reference = AAZStrType(
            serialized_name="stageReference",
            flags={"required": True},
        )
        properties.stage_variables = AAZDictType(
            serialized_name="stageVariables",
        )
        properties.status = AAZStrType(
            flags={"required": True},
        )

        links = _schema_stage_progression_read.properties.links
        links.Element = AAZObjectType()

        _element = _schema_stage_progression_read.properties.links.Element
        _element.description = AAZStrType()
        _element.name = AAZStrType(
            flags={"required": True},
        )
        _element.uri = AAZStrType(
            flags={"required": True},
        )

        parameters = _schema_stage_progression_read.properties.parameters
        parameters.Element = AAZAnyType()

        stage_variables = _schema_stage_progression_read.properties.stage_variables
        stage_variables.Element = AAZAnyType()

        system_data = _schema_stage_progression_read.system_data
        system_data.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        _schema.id = cls._schema_stage_progression_read.id
        _schema.name = cls._schema_stage_progression_read.name
        _schema.properties = cls._schema_stage_progression_read.properties
        _schema.system_data = cls._schema_stage_progression_read.system_data
        _schema.type = cls._schema_stage_progression_read.type


__all__ = ["Update"]
