files_check:
  - files:
      - "src/.*/HISTORY.rst"
      - "src/.*/setup.py"
    comment: |
      Please write the description of changes which can be perceived by customers into HISTORY.rst.
      If you want to release a new extension version, please update the version in setup.py as well.
    is_regex: true
    type: necessary
allowed_branches:
  - "main"
auto_choose_milestone:
  pr_expected_days: 7
