files_check:
  - files:
      - "HISTORY.rst"
      - "setup.py"
    comment: |
      If you want to release the new extension version.
      Please write the description of changes into HISTORY.rst and update setup.py.
allowed_branches:
  - "main"
auto_choose_milestone:
  pr_expected_days: 7
