# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
stages:
- stage: LintAndStyle
  jobs:
  - job: LintAndStyle
    displayName: 'Verify linting and style formatting'
    pool:
      type: linux
    variables:
    - name: ob_outputDirectory
      value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
    - name: ob_sdl_codeql_compiled_enabled
      value: false
    steps:
    - task: PipAuthenticate@1
      displayName: Authenticate to Artifacts (pip)
      inputs:
        artifactFeeds: 'Tina/Tina_PublicPackages'
    - task: CmdLine@2
      displayName: 'Run linting and style formatting'
      inputs:
        script: scripts/ci/lint/pipeline.sh
        workingDirectory: $(Build.SourcesCliDirectory)
      env:
        PAT_TOKEN: $(System.AccessToken) 