# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "logic integration-account batch-configuration update",
)
class Update(AAZCommand):
    """Update a batch configuration for an integration account.

    :example: Update batch configuration
        az logic integration-account batch-configuration update -g rg -n batch --integration-account-name name --release-criteria '{recurrence:{frequency:Minute,interval:2},messageCount:20,batchSize:12000}'
    """

    _aaz_info = {
        "version": "2019-05-01",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.logic/integrationaccounts/{}/batchconfigurations/{}", "2019-05-01"],
        ]
    }

    AZ_SUPPORT_GENERIC_UPDATE = True

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.batch_configuration_name = AAZStrArg(
            options=["-n", "--name", "--batch-configuration-name"],
            help="The batch configuration name.",
            required=True,
            id_part="child_name_1",
        )
        _args_schema.integration_account_name = AAZStrArg(
            options=["--integration-account-name"],
            help="The integration account name.",
            required=True,
            id_part="name",
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "BatchConfiguration"

        _args_schema = cls._args_schema
        _args_schema.location = AAZResourceLocationArg(
            arg_group="BatchConfiguration",
            help="The resource location.",
            nullable=True,
            fmt=AAZResourceLocationArgFormat(
                resource_group_arg="resource_group",
            ),
        )
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            arg_group="BatchConfiguration",
            help="The resource tags.",
            nullable=True,
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg(
            nullable=True,
        )

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.batch_group_name = AAZStrArg(
            options=["--batch-group-name"],
            arg_group="Properties",
            help="The name of the batch group.",
        )
        _args_schema.changed_time = AAZDateTimeArg(
            options=["--changed-time"],
            arg_group="Properties",
            help="The changed time.",
            nullable=True,
        )
        _args_schema.created_time = AAZDateTimeArg(
            options=["--created-time"],
            arg_group="Properties",
            help="The created time.",
            nullable=True,
        )
        _args_schema.metadata = AAZFreeFormDictArg(
            options=["--metadata"],
            arg_group="Properties",
            help="The metadata",
            nullable=True,
        )
        _args_schema.release_criteria = AAZObjectArg(
            options=["--release-criteria"],
            arg_group="Properties",
            help="The batch release criteria.",
        )

        release_criteria = cls._args_schema.release_criteria
        release_criteria.batch_size = AAZIntArg(
            options=["batch-size"],
            help="The batch size in bytes.",
            nullable=True,
        )
        release_criteria.message_count = AAZIntArg(
            options=["message-count"],
            help="The message count.",
            nullable=True,
        )
        release_criteria.recurrence = AAZObjectArg(
            options=["recurrence"],
            help="The recurrence.",
            nullable=True,
        )

        recurrence = cls._args_schema.release_criteria.recurrence
        recurrence.end_time = AAZStrArg(
            options=["end-time"],
            help="The end time.",
            nullable=True,
        )
        recurrence.frequency = AAZStrArg(
            options=["frequency"],
            help="The frequency.",
            nullable=True,
            enum={"Day": "Day", "Hour": "Hour", "Minute": "Minute", "Month": "Month", "NotSpecified": "NotSpecified", "Second": "Second", "Week": "Week", "Year": "Year"},
        )
        recurrence.interval = AAZIntArg(
            options=["interval"],
            help="The interval.",
            nullable=True,
        )
        recurrence.schedule = AAZObjectArg(
            options=["schedule"],
            help="The recurrence schedule.",
            nullable=True,
        )
        recurrence.start_time = AAZStrArg(
            options=["start-time"],
            help="The start time.",
            nullable=True,
        )
        recurrence.time_zone = AAZStrArg(
            options=["time-zone"],
            help="The time zone.",
            nullable=True,
        )

        schedule = cls._args_schema.release_criteria.recurrence.schedule
        schedule.hours = AAZListArg(
            options=["hours"],
            help="The hours.",
            nullable=True,
        )
        schedule.minutes = AAZListArg(
            options=["minutes"],
            help="The minutes.",
            nullable=True,
        )
        schedule.month_days = AAZListArg(
            options=["month-days"],
            help="The month days.",
            nullable=True,
        )
        schedule.monthly_occurrences = AAZListArg(
            options=["monthly-occurrences"],
            help="The monthly occurrences.",
            nullable=True,
        )
        schedule.week_days = AAZListArg(
            options=["week-days"],
            help="The days of the week.",
            nullable=True,
        )

        hours = cls._args_schema.release_criteria.recurrence.schedule.hours
        hours.Element = AAZIntArg(
            nullable=True,
        )

        minutes = cls._args_schema.release_criteria.recurrence.schedule.minutes
        minutes.Element = AAZIntArg(
            nullable=True,
        )

        month_days = cls._args_schema.release_criteria.recurrence.schedule.month_days
        month_days.Element = AAZIntArg(
            nullable=True,
        )

        monthly_occurrences = cls._args_schema.release_criteria.recurrence.schedule.monthly_occurrences
        monthly_occurrences.Element = AAZObjectArg(
            nullable=True,
        )

        _element = cls._args_schema.release_criteria.recurrence.schedule.monthly_occurrences.Element
        _element.day = AAZStrArg(
            options=["day"],
            help="The day of the week.",
            nullable=True,
            enum={"Friday": "Friday", "Monday": "Monday", "Saturday": "Saturday", "Sunday": "Sunday", "Thursday": "Thursday", "Tuesday": "Tuesday", "Wednesday": "Wednesday"},
        )
        _element.occurrence = AAZIntArg(
            options=["occurrence"],
            help="The occurrence.",
            nullable=True,
        )

        week_days = cls._args_schema.release_criteria.recurrence.schedule.week_days
        week_days.Element = AAZStrArg(
            nullable=True,
            enum={"Friday": "Friday", "Monday": "Monday", "Saturday": "Saturday", "Sunday": "Sunday", "Thursday": "Thursday", "Tuesday": "Tuesday", "Wednesday": "Wednesday"},
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.IntegrationAccountBatchConfigurationsGet(ctx=self.ctx)()
        self.pre_instance_update(self.ctx.vars.instance)
        self.InstanceUpdateByJson(ctx=self.ctx)()
        self.InstanceUpdateByGeneric(ctx=self.ctx)()
        self.post_instance_update(self.ctx.vars.instance)
        self.IntegrationAccountBatchConfigurationsCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    @register_callback
    def pre_instance_update(self, instance):
        pass

    @register_callback
    def post_instance_update(self, instance):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class IntegrationAccountBatchConfigurationsGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/integrationAccounts/{integrationAccountName}/batchConfigurations/{batchConfigurationName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "ODataV4Format"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "batchConfigurationName", self.ctx.args.batch_configuration_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "integrationAccountName", self.ctx.args.integration_account_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2019-05-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()
            _UpdateHelper._build_schema_batch_configuration_read(cls._schema_on_200)

            return cls._schema_on_200

    class IntegrationAccountBatchConfigurationsCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200, 201]:
                return self.on_200_201(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/integrationAccounts/{integrationAccountName}/batchConfigurations/{batchConfigurationName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "ODataV4Format"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "batchConfigurationName", self.ctx.args.batch_configuration_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "integrationAccountName", self.ctx.args.integration_account_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2019-05-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=self.ctx.vars.instance,
            )

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()
            _UpdateHelper._build_schema_batch_configuration_read(cls._schema_on_200_201)

            return cls._schema_on_200_201

    class InstanceUpdateByJson(AAZJsonInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance(self.ctx.vars.instance)

        def _update_instance(self, instance):
            _instance_value, _builder = self.new_content_builder(
                self.ctx.args,
                value=instance,
                typ=AAZObjectType
            )
            _builder.set_prop("location", AAZStrType, ".location")
            _builder.set_prop("properties", AAZObjectType, ".", typ_kwargs={"flags": {"required": True}})
            _builder.set_prop("tags", AAZDictType, ".tags")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("batchGroupName", AAZStrType, ".batch_group_name", typ_kwargs={"flags": {"required": True}})
                properties.set_prop("changedTime", AAZStrType, ".changed_time")
                properties.set_prop("createdTime", AAZStrType, ".created_time")
                properties.set_prop("metadata", AAZFreeFormDictType, ".metadata")
                properties.set_prop("releaseCriteria", AAZObjectType, ".release_criteria", typ_kwargs={"flags": {"required": True}})

            metadata = _builder.get(".properties.metadata")
            if metadata is not None:
                metadata.set_anytype_elements(".")

            release_criteria = _builder.get(".properties.releaseCriteria")
            if release_criteria is not None:
                release_criteria.set_prop("batchSize", AAZIntType, ".batch_size")
                release_criteria.set_prop("messageCount", AAZIntType, ".message_count")
                release_criteria.set_prop("recurrence", AAZObjectType, ".recurrence")

            recurrence = _builder.get(".properties.releaseCriteria.recurrence")
            if recurrence is not None:
                recurrence.set_prop("endTime", AAZStrType, ".end_time")
                recurrence.set_prop("frequency", AAZStrType, ".frequency")
                recurrence.set_prop("interval", AAZIntType, ".interval")
                recurrence.set_prop("schedule", AAZObjectType, ".schedule")
                recurrence.set_prop("startTime", AAZStrType, ".start_time")
                recurrence.set_prop("timeZone", AAZStrType, ".time_zone")

            schedule = _builder.get(".properties.releaseCriteria.recurrence.schedule")
            if schedule is not None:
                schedule.set_prop("hours", AAZListType, ".hours")
                schedule.set_prop("minutes", AAZListType, ".minutes")
                schedule.set_prop("monthDays", AAZListType, ".month_days")
                schedule.set_prop("monthlyOccurrences", AAZListType, ".monthly_occurrences")
                schedule.set_prop("weekDays", AAZListType, ".week_days")

            hours = _builder.get(".properties.releaseCriteria.recurrence.schedule.hours")
            if hours is not None:
                hours.set_elements(AAZIntType, ".")

            minutes = _builder.get(".properties.releaseCriteria.recurrence.schedule.minutes")
            if minutes is not None:
                minutes.set_elements(AAZIntType, ".")

            month_days = _builder.get(".properties.releaseCriteria.recurrence.schedule.monthDays")
            if month_days is not None:
                month_days.set_elements(AAZIntType, ".")

            monthly_occurrences = _builder.get(".properties.releaseCriteria.recurrence.schedule.monthlyOccurrences")
            if monthly_occurrences is not None:
                monthly_occurrences.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".properties.releaseCriteria.recurrence.schedule.monthlyOccurrences[]")
            if _elements is not None:
                _elements.set_prop("day", AAZStrType, ".day")
                _elements.set_prop("occurrence", AAZIntType, ".occurrence")

            week_days = _builder.get(".properties.releaseCriteria.recurrence.schedule.weekDays")
            if week_days is not None:
                week_days.set_elements(AAZStrType, ".")

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")

            return _instance_value

    class InstanceUpdateByGeneric(AAZGenericInstanceUpdateOperation):

        def __call__(self, *args, **kwargs):
            self._update_instance_by_generic(
                self.ctx.vars.instance,
                self.ctx.generic_update_args
            )


class _UpdateHelper:
    """Helper class for Update"""

    _schema_batch_configuration_read = None

    @classmethod
    def _build_schema_batch_configuration_read(cls, _schema):
        if cls._schema_batch_configuration_read is not None:
            _schema.id = cls._schema_batch_configuration_read.id
            _schema.location = cls._schema_batch_configuration_read.location
            _schema.name = cls._schema_batch_configuration_read.name
            _schema.properties = cls._schema_batch_configuration_read.properties
            _schema.tags = cls._schema_batch_configuration_read.tags
            _schema.type = cls._schema_batch_configuration_read.type
            return

        cls._schema_batch_configuration_read = _schema_batch_configuration_read = AAZObjectType()

        batch_configuration_read = _schema_batch_configuration_read
        batch_configuration_read.id = AAZStrType(
            flags={"read_only": True},
        )
        batch_configuration_read.location = AAZStrType()
        batch_configuration_read.name = AAZStrType(
            flags={"read_only": True},
        )
        batch_configuration_read.properties = AAZObjectType(
            flags={"required": True},
        )
        batch_configuration_read.tags = AAZDictType()
        batch_configuration_read.type = AAZStrType(
            flags={"read_only": True},
        )

        properties = _schema_batch_configuration_read.properties
        properties.batch_group_name = AAZStrType(
            serialized_name="batchGroupName",
            flags={"required": True},
        )
        properties.changed_time = AAZStrType(
            serialized_name="changedTime",
        )
        properties.created_time = AAZStrType(
            serialized_name="createdTime",
        )
        properties.metadata = AAZFreeFormDictType()
        properties.release_criteria = AAZObjectType(
            serialized_name="releaseCriteria",
            flags={"required": True},
        )

        release_criteria = _schema_batch_configuration_read.properties.release_criteria
        release_criteria.batch_size = AAZIntType(
            serialized_name="batchSize",
        )
        release_criteria.message_count = AAZIntType(
            serialized_name="messageCount",
        )
        release_criteria.recurrence = AAZObjectType()

        recurrence = _schema_batch_configuration_read.properties.release_criteria.recurrence
        recurrence.end_time = AAZStrType(
            serialized_name="endTime",
        )
        recurrence.frequency = AAZStrType()
        recurrence.interval = AAZIntType()
        recurrence.schedule = AAZObjectType()
        recurrence.start_time = AAZStrType(
            serialized_name="startTime",
        )
        recurrence.time_zone = AAZStrType(
            serialized_name="timeZone",
        )

        schedule = _schema_batch_configuration_read.properties.release_criteria.recurrence.schedule
        schedule.hours = AAZListType()
        schedule.minutes = AAZListType()
        schedule.month_days = AAZListType(
            serialized_name="monthDays",
        )
        schedule.monthly_occurrences = AAZListType(
            serialized_name="monthlyOccurrences",
        )
        schedule.week_days = AAZListType(
            serialized_name="weekDays",
        )

        hours = _schema_batch_configuration_read.properties.release_criteria.recurrence.schedule.hours
        hours.Element = AAZIntType()

        minutes = _schema_batch_configuration_read.properties.release_criteria.recurrence.schedule.minutes
        minutes.Element = AAZIntType()

        month_days = _schema_batch_configuration_read.properties.release_criteria.recurrence.schedule.month_days
        month_days.Element = AAZIntType()

        monthly_occurrences = _schema_batch_configuration_read.properties.release_criteria.recurrence.schedule.monthly_occurrences
        monthly_occurrences.Element = AAZObjectType()

        _element = _schema_batch_configuration_read.properties.release_criteria.recurrence.schedule.monthly_occurrences.Element
        _element.day = AAZStrType()
        _element.occurrence = AAZIntType()

        week_days = _schema_batch_configuration_read.properties.release_criteria.recurrence.schedule.week_days
        week_days.Element = AAZStrType()

        tags = _schema_batch_configuration_read.tags
        tags.Element = AAZStrType()

        _schema.id = cls._schema_batch_configuration_read.id
        _schema.location = cls._schema_batch_configuration_read.location
        _schema.name = cls._schema_batch_configuration_read.name
        _schema.properties = cls._schema_batch_configuration_read.properties
        _schema.tags = cls._schema_batch_configuration_read.tags
        _schema.type = cls._schema_batch_configuration_read.type


__all__ = ["Update"]
