#!E:\Projects\AzureCLI\azure-cli-extensions\e-env\Scripts\python.exe

import sys
import os

dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'src')

if os.environ.get('PYTHONPATH') == None:
    os.environ['PYTHONPATH'] = dir
else:
    os.environ['PYTHONPATH'] = os.pathsep.join([
        dir,
        os.environ.get('PYTHONPATH'),
    ])

os.execl(sys.executable, sys.executable , '-m', 'azure.cli', *sys.argv[1:])
