# GitHub Release v1.0.0
resources:
  - repo: self
  
trigger: none
  
pr:
    branches:
      include:
      - '*'
pool:
    vmImage: 'ubuntu-latest'
  
variables:
    pythonVersion: '3.12'
    venvDir: '$(Pipeline.Workspace)/venv'
  
jobs:
  - job: BuildAndDeploy
    displayName: "Build and Deploy"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      fetchDepth: 0
      fetchTags: true

    - task: Docker@2 
      displayName: 'Clone and Setup Azure-cli Repository' 
      inputs: 
        containerRegistry: '$(kraterdevteam)' 
        repository: 'python' 
        command: 'run' 
        arguments: '--rm -v $(Pipeline.Workspace):/workspace -w /workspace python:$(pythonVersion) /bin/bash -c " 
          git clone https://github.com/Azure/azure-cli-dev-tools.git 
          cd azure-cli 
          git remote add upstream https://github.com/Azure/azure-cli-dev-tools.git  
          git fetch upstream 
          git branch dev --set-upstream-to upstream/dev 
          git checkout -b feature_branch 
        "'   
    - task: Docker@2 
      displayName: 'Clone and Setup Azure-Cli-Extension Repository' 
      inputs: 
        containerRegistry: '$(kraterdevteam)' 
        repository: 'python' 
        command: 'run' 
        arguments: '--rm -v $(Pipeline.Workspace):/workspace -w /workspace python:$(pythonVersion) /bin/bash -c " 
          git clone https://github.com/AzureCR/azure-cli-extensions.git 
          cd azure-cli-extensions 
          git remote add upstream https://github.com/AzureCR/azure-cli-extensions.git 
          git fetch upstream 
          git branch main --set-upstream-to upstream/main 
          git checkout -b feature_branch 
        "' 
    - task: Docker@2 
      displayName: 'Setup Python Environment and Build' 
      inputs: 
        containerRegistry: '$(kraterdevteam)' 
        repository: 'python' 
        command: 'run' 
        arguments: '--rm -v $(Pipeline.Workspace):/workspace -w /workspace python:$(pythonVersion) /bin/bash -c " 
          python -m venv $(venvDir) && source $(venvDir)/bin/activate
          python -m pip install --upgrade pip && pip install setuptools==70.0.0 && pip install --force-reinstall wheel==0.30.0  
          pip install azdev && azdev setup -c -r azure-cli-extensions && azdev extension build acrcache 
        "' 