# Default values for sample-chart
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Custom configuration section for wo_gen.py testing
config:
  name: "default-config"
  version: "1.0.0"
  settings:
    enabled: true
    feature1: true
    feature2: false
  endpoints:
    - name: "primary"
      url: "http://example.com"
    - name: "secondary"
      url: "http://backup.example.com"
