name: Comment Issue when labeled non-security
on:
  issues:
    types: [opened, labeled, unlabeled]

jobs:
  comment-non-security:
    if: contains(github.event.issue.labels.*.name, 'non-security')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    name: Comment on issue
    steps:
      - name: Checkout comment message
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          sparse-checkout: |
            .github/template/non-security-comment.md
      - name: Comment on issue with no security label
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           message-id: issueNoSecurityCommentBot
           message-path: |
            .github/template/non-security-comment.md
