on:
  issues:
    types: [opened]
   
jobs:
  thank-user:
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    name: Say thanks for the Issue
    steps:
      - name: comment on the issue
        uses: hasura/comment-progress@146c635f3e325d478025e29e5043ec1c07c0e36c # v2.3.0
        with:
          github-token: ${{ secrets.CLI_BOT }}
          repository: 'Azure/azure-cli-extensions'
          number: ${{ github.event.issue.number }}
          id: thank-you-comment
          message: 'Thank you for opening this issue, we will look into it.'
