name: CD

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Setup development environment
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install -U pip
        pip install azdev
        azdev setup -r .
        azdev extension add apic-extension

    # Append commit hash to the version. E.g. 1.0.0b4+abc1234
    - name: Generate and update version
      run: |
        python ./github/workflows/update_version.py

    - name: Build binary
      run: |
        source .venv/bin/activate
        azdev extension build apic-extension

    - name: Upload release asset
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: |
          ./dist/*.whl