name: Style and Lint Check

on:
  pull_request:
    types: [opened]

jobs:
  build_aosm:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli/tools:latest
    permissions: write-all
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check Style
        run: azdev style aosm
      - name: Check Linting
        run: azdev linter aosm