# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_dispatch:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        cd src/connectedk8s
        ls
        printf "[bdist_wheel]\nuniversal=1\n" > setup.cfg
        python setup.py sdist bdist_wheel
        cd dist
        ls
    - name: publish .whl
      uses: actions/upload-artifact@v2
      with:
        name: connectedk8s-whl
        path: src/connectedk8s/dist/connectedk8s-*.whl
