name: Test OIDC claims
on:
  push:
  workflow_dispatch:
      
jobs:
  oidc_debug_test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
    - name: Debug OIDC Claims
      uses: github/actions-oidc-debugger@main
      with:
        audience: 'api://AzureADTokenExchange'
